# Generated by Django 5.0.14 on 2025-06-13 19:20

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_song_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='audio_file',
            field=models.FileField(upload_to=api.models.clean_audio_filename),
        ),
        migrations.AlterField(
            model_name='song',
            name='cover_image',
            field=models.FileField(upload_to=api.models.clean_cover_filename),
        ),
    ]
