# Generated by Django 5.0.14 on 2025-06-16 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_song_audio_file_alter_song_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='playlist_covers/'),
        ),
    ]
