# Generated by Django 5.0.14 on 2025-06-17 15:26

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_playlist_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_broadcast',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='song',
            name='cover_image',
            field=models.ImageField(upload_to=api.models.clean_cover_filename),
        ),
    ]
